# Example MongoDB configuration
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      # ME_CONFIG_MONGODB_ADMINUSERNAME: root
      # ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017
      ME_CONFIG_BASICAUTH: false

  sugarcubed:
    build: ..
    depends_on:
      - mongo
    ports:
      - 8080:8080
    environment:
      - SUGARCUBE_DB_URI=mongo
      - SUGARCUBE_DB_PORT=27017
      - SUGARCUBE_PORT=8080
      - SUGARCUBE_DEBUG=false
    restart: always
